### ISSUE TITLE
Icons shown as blank since 1.5.1.1

### ISSUE THREAD

**Issue by iccfish** [rionmonster/Glyphfriend#62] opened 2016-09-05 12:33 UTC
Just create a new website on local driver and install bootstrap 3.x via nuget, but I get icons shown in intellisense window totally, just showing blank icon.

See image: ![Pic](http://i63.tinypic.com/osbsw0.jpg)

I've tested many versions, found version 1.5.0 works, but since 1.5.1.1 this problem comes out, I think this may be due to new the async load method.

**Comment by rionmonster** [comment] 2016-09-05 16:09
Thanks for reporting this.

I just recently noticed it myself and it seems related to the asynchronous loading that was implemented in 1.5.1.1 to improve performance. I haven't singled out a fix yet (a `ConcurrentDictionary` implementation might help). I'll let you know when something resolves it.

**Comment by rionmonster** [comment] 2016-09-10 14:20
Just checking into this again and trying to consistently reproduce it. 

Can you tell me a bit more about your environment? Specifically which version of Visual Studio 2015 you are running (i.e Update 1, 2, or 3)?

**Comment by Jan-Kruse** [comment] 2016-09-12 07:37
I am running Update 3 on my machine and can reproduce the error, too.

**Comment by rionmonster** [comment] 2016-09-12 13:05
Thanks @Jan-Kruse,

I was finally able to reproduce it on the same machine after updating it to Update 3 (from Update 1), however it seems hit or miss with regards to reproducability.

**Comment by LukaszRabiec** [comment] 2016-09-22 12:28
I have a similar problem, instead of the icon shows one pattern image. The problem occurs in VS 2k15 U3 with the extension in the latest version and 1.5.0

![chrome_2016-09-22_14-08-50](https://cloud.githubusercontent.com/assets/9741188/18748020/b5a3a036-80d0-11e6-9128-0186929a2a67.png)

It's any solution for this?

**Comment by rionmonster** [comment] 2016-09-22 13:08
@LukaszRabiec 

Those glyphs look quite a bit different. Do you have Resharper installed? If so, you'll need to actually use the [Glyphfriend for Resharper plug-in](https://resharper-plugins.jetbrains.com/packages/Hunt.ResharperGlyphfriend/) in order to get things working properly or simply disable HTML autocompletion in Resharper and let Visual Studio handle it for you.

**Comment by rionmonster** [comment] 2016-09-22 13:12
**Update**

I've been working with a few members of the Visual Studio and Visual Studio extensibility teams regarding this issue and we have tested out several approaches to resolve the asynchronous loading issues (i.e. the blank icons). What we discovered during this time was in fact a bug within the Visual Studio API, which will need to be resolved before a fix can be issued.

As mentioned, you can [download either v1.5.0 or v1.5.1 of the extension directly through the Releases](https://github.com/rionmonster/Glyphfriend/releases) tab of this repository as a temporary fix.

**Comment by LukaszRabiec** [comment] 2016-09-22 15:02
Yea, I have Resharper (version 2016.2.2) and when I go to ReSharper Extension Manager (Resharper Ultimate Extensions) I can see only 50 available extensions :/ In Extension Manager options is this path: https://resharper-plugins.jetbrains.com/api/v2/curated-feeds/Wave_v6.0/

I tried to download a file from page specified by You and specify the path to it, but unfortunately the manager can't see this .nupkg

You have any advice on this? Maybe I'm doing something wrong...

**Comment by datvm** [comment] 2016-09-26 15:18
Hi currently I have Glyphfriend version 1.5.1.3 (from Visual Studio Gallery I think, since I see the newest release is just 1.5.1.1), Visual Studio 2015 Update 3 (Enterprise version). I also have this issue, both Font Awesome and Bootstrap icons.

**Comment by rionmonster** [comment] 2016-09-26 17:41
Hi @datvm 

As I mentioned a bit earlier, this is the result of the asynchronous loading changes that were released 1.5.1.1 (which is roughly equivalent to 1.5.1.3 as there were some rollback issues in the gallery and those weren't formally released). 

The current workaround however is to use either v1.5.0 or v1.5.1 versions available from the Releases area of this repository. We discovered a bug when trying to resolve the asynchronicity issues with Visual Studio's API and cannot fix the issue until that is resolved.

**Comment by datvm** [comment] 2016-09-26 17:57
Thanks! I thought 1.5.1.3 includes the fix. Just a confirmation though, I will stick with the Workaround for now.

Great extension btw, really helpful. I hope you guys will get the API patched soon.

**Comment by Jotting89** [comment] 2016-10-08 09:28
fixed version
https://1drv.ms/u/s!Ap1x2xID9EAkiMEuJzVFFpieMt7wXw

**Comment by Jotting89** [comment] 2016-10-08 09:33
fixed async version
[Glyphfriend.zip](https://github.com/rionmonster/Glyphfriend/files/517569/Glyphfriend.zip)

**Comment by rionmonster** [comment] 2016-10-11 15:07
@Jotting89

Wow, I had actually implemented the proposed changes that you included within your original post on this thread (last Friday) into the project and everything appears to work as expected. I have a PR coming with several other enhancements that I was working on previously that should be released today (with your changes included).

**Comment by rionmonster** [comment] 2016-10-11 15:21
This issue should be resolved in the latest release of the extension (v1.5.2.0), which was just pushed up to the gallery. I greatly appreciate everyone that helped out with the issue, both in this thread and outside of it (via e-mail, etc.)

Once again, a huge shout-out to [Jotting89](https://github.com/Jotting89) for his help with the asynchronous resolution.

**Closed by rionmonster** 2016-10-11 15:21 UTC
